homeassistant:
  name: Home
  latitude: 51.151682
  longitude: 6.064496
  elevation: 27
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

automation: !include_dir_list automation
group: !include groups.yaml
sensor: !include sensor.yaml
sensor mqtt: !include sensor_mqtt.yaml
sensor template: !include sensor_template.yaml
binary_sensor: !include sensor_binary.yaml
binary_sensor trend: !include sensor_trend.yaml
scene: !include scenes.yaml
light: !include light.yaml
switch: !include switch.yaml

zone:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 500
  icon: mdi:worker

logger:
  default: info
  # logs:
  #   mysensors.mysensors: debug

sun:
frontend:
history:
updater:
logbook:
ios:

recorder:
  purge_days: 7
  db_url: mysql://homeassistant:homeassistant@10.0.1.13:3306/homeassistant

http:
  api_password: !secret http_password
  server_port: 8124
  ssl_certificate: /etc/letsencrypt/live/koen01.synology.me/fullchain.pem
  ssl_key: /etc/letsencrypt/live/koen01.synology.me/privkey.pem

mqtt:
  broker: 10.0.1.59
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

mqtt_export:
  publish_topic: "home/states"

alarm_control_panel:
  platform: manual

thingspeak:
  api_key: IXN070RXZME6PG92
  id: 203628
  whitelist: sensor.netatmo_buiten_temperature

influxdb:
  host: 127.0.0.1
  database: home_assistant
  username: !secret influx_user
  password: !secret influx_password

device_tracker:
  - platform: owntracks

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

notify telegram:
  name: telegram_koen
  platform: telegram
  api_key: !secret telegram_api_key
  chat_id: !secret telegram_chat_id

sensor plants:
  - platform: miflora
    mac: C4:7C:8D:60:BD:4D
    name: plant 1
    force_update: false
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
  - platform: miflora
    mac: C4:7C:8D:60:BF:D1
    name: plant 2
    force_update: false
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity

camera:
  - platform: foscam
    ip: 10.0.1.35
    name: Schuur
    port: 88
    username: !secret foscam_username
    password: !secret foscam_password

  - platform: mjpeg
    mjpeg_url: http://10.0.1.20:99/videostream.cgi
    name: Kippenhok
    username: !secret kippenhok_user
    password: !secret kippenhok_password

  - platform: foscam
    ip: 10.0.1.16
    name: C1
    port: 88
    username: !secret foscam_username
    password: !secret foscam_password

  - platform: generic
    still_image_url: http://api.buienradar.nl/image/1.0/RadarMapNL?w=500&h=512
    name: Neerslag radar
  - platform: generic
    still_image_url: http://cdn.knmi.nl/knmi/map/page/weer/actueel-weer/temperatuur.png
    name: Huidig

rfxtrx:
  device: '/dev/ttyUSB-RFX433'
  debug: True
  dummy: False

mysensors:
  gateways:
    # - device: '10.0.1.17'
    #   persistence_file: '/home/hass/.homeassistant/mysensors.json'
    #   tcp_port: 5003
    - device: mqtt
      persistence_file: '/home/hass/.homeassistant/mysensors_mqtt.json'
      topic_in_prefix: 'mygateway1-out'
      topic_out_prefix: 'mygateway1-in'
  debug: True
  persistence: True
  version: '2.0'
  retain: true
  optimistic: false

media_player:
  platform: kodi
  host: http://10.0.1.19
  port: 8080
  name: Kodi
  username: 1234
  password: 1234
  turn_off_action: shutdown

cover:
  platform: rfxtrx
  devices:
    071a000000000001:
      name: Carport

input_slider:
  sprinklertimer:
    name: Sprinkler timer
    icon: mdi:clock
    initial: 45
    min: 0
    max: 60
    step: 5

input_select:
  camera_presets:
    name: Camera presets
    options:
     - Preset 1
     - Preset 2
     - Preset 3
     - Preset 4
    initial: Preset 1
    icon: mdi:video

input_boolean:
  notify_doors:
    name: Notify when doors open
    initial: off
    icon: mdi:alert-circle-outline
  sprinkler:
    name: Sprinkler program
    initial: off
    icon: mdi:timer

shell_command:
  camera_preset_1: !secret camera_preset_1
  camera_preset_2: !secret camera_preset_2
  camera_preset_3: !secret camera_preset_3
  camera_preset_4: !secret camera_preset_4
  mindergas: /home/pi/mindergas/mindergas_mqtt.py

script:
  mindergas:
    alias: Upload gas usage
    sequence:
      - service: shell_command.mindergas
