- platform: mqtt
  state_topic: "ipcamera/schuur"
  name: "Camera motion"
  qos: 0
  payload_on: "2"
  payload_off: "1"
  sensor_class: motion
  value_template: '{{ value_json.motionDetectAlarm }}'
- platform: mqtt
  state_topic: "mygateway1-out/47/3/1/0/16"
  name: "Cube activity"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  sensor_class: moving
  value_template: '{{ value }}'
- platform: mqtt
  state_topic: "mygateway1-out/47/2/1/0/2"
  name: "Cube tap"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  value_template: '{{ value }}'
