alias: 'Turn off porchlight at 00:00'
trigger:
  platform: time
  after: '00:00:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
    service: homeassistant.turn_off
    entity_id: switch.buitenlamp
