alias: 'Chickencoop closed'
trigger:
  platform: state
  entity_id: sensor.chickencoop
  from: 'false'
  to: 'true'
action:
  - service: shell_command.camera_preset_3
  - delay: 00:00:40
  - service: notify.telegram_koen
    data:
      title: ''
      message: ''
      data:
        photo:
          - url: http://10.0.1.20:99/snapshot.cgi
            username: !secret wanscam_user
            password: !secret wanscam_password
            caption: Kippenhok just closed
  - delay: 00:00:10
  - service: shell_command.camera_preset_4
  - delay: 00:00:30
  - service: notify.telegram_koen
    data:
      title: ''
      message: ''
      data:
        photo:
          - url: http://10.0.1.20:99/snapshot.cgi
            username: !secret wanscam_user
            password: !secret wanscam_password
            caption: Kippenhok closed
