alias: 'Chickencoop open'
trigger:
  platform: state
  entity_id: sensor.chickencoop
  from: 'true'
  to: 'false'
action:
  - service: shell_command.camera_preset_1
  - delay: 00:00:40
  - service: notify.telegram_koen
    data:
      title: ''
      message: ''
      data:
        photo:
          - url: http://10.0.1.20:99/snapshot.cgi
            username: !secret wanscam_user
            password: !secret wanscam_password
            caption: Kippenhok just opened
