alias: 'Turn on christmas lights at 09:15'
trigger:
  platform: time
  after: '08:15:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
    service: homeassistant.turn_on
    entity_id: switch.kerstboom
