alias: 'Turn of christmas lights at 22:15'
trigger:
  platform: time
  after: '22:15:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
    service: homeassistant.turn_off
    entity_id: switch.kerstboom
