alias: Doorbell  pressed
trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
action:
  service: notify.telegram_koen
  data:
    title: Doorbell pressed!
    message: Doorbell pressed  {{ now }}!
    data:
      photo:
        - url: !secret foscam_url
          caption: Doorbell pressed  {{ now() }}
