alias: Molgan sensor on
trigger:
  platform: state
  entity_id: binary_sensor.molgan_sensor_41_1
  to: 'on'
condition:
  condition: template
  value_template: '{{ states.sun.sun.attributes.elevation < 3.5 }}'
action:
  service: homeassistant.turn_on
  entity_id: switch.molgan_sensor_41_2
