alias: 'Turn lights off when lux > 500'
trigger:
  platform: numeric_state
  entity_id: sensor.chickencoop_l298n_3_0
  value_template: '{{ state.attributes.V_LEVEL }}'
  above: 500
condition:
  condition: state
  entity_id: group.all_devices
  state: home
action:
  - service: homeassistant.turn_off
    entity_id: group.woonkamer_lights
  - service: notify.telegram_koen
    data:
     title: ''
     message: auto lux {{ now() }}
